### ISSUE TITLE
Napsat specifikaci

### ISSUE THREAD

**Issue by OndrejPittl** [Sekiphp/ZSWI_monitoring#12]
Je třeba začít psát specifikaci. Příští týden je konzultace ohledně specifikací, možná by bylo fajn přijít.

**Comment by Sekiphp** [comment]
Dneska jsme na tom s Petrem mákli. Něco ale chybí, takže bude dobré, když to ještě někdo projde :) Připomínky dyštak sem, nebo na FB :)

díky
