### ISSUE TITLE
Workshop o GitHUBu

### ISSUE THREAD

**Issue by OndrejPittl** [Sekiphp/ZSWI_monitoring#13]
V pondělí <strong>2. 3. od 15:00</strong> se koná v prostorách NTIS — učebna <strong>UC-311</strong> workshop (s praktickými ukázkami) práce s Gitem. Délka workshopu je <strong>2 hodiny</strong>. Volných míst bude asi dost, moc zájem o to nebyl, přesto si myslím, že bude přínosná (předpokládám, že se GitHUB apod. jen tak používat nepřestane). Z našeho týmu se jí zatím účastníme: Ondra, Luboš, Jiří.

**Comment by kohlicekjan** [comment]
Rád se zúčastním, jen nevím, kde se mám registrovat?

**Comment by pkozler** [comment]
Taky bych se zúčastnil, kdybych věděl, jak se na workshop zapsat?

**Comment by kohlicekjan** [comment]
Takže tam mužem přijít jen tak?

**Comment by OndrejPittl** [comment]
Pardon za zpoždění. Ano, jen tak. Není třeba se nikde zapisovat :+1:
