### ISSUE TITLE
Příprava k pohovoru

### ISSUE THREAD

**Issue by OndrejPittl** [Sekiphp/ZSWI_monitoring#14]
Potřebuju od někoho, kdo nemá, co dělat, aby prošel template specifikace na <strong>CW > ZSWI > Samostatná práce</strong> (vpravo dole), Issues a stránky Unicorn Systems a zkontroloval, co nevíme. Na to bude potřeba se zadavatele <strong>v pátek</strong> poptat.

**Comment by jhomolka** [comment]
Já se na to během dneška podívám, sepíšu nějaká body a během zítřka ( nejspíš asi behem prednasky na NM) to doladíme, abyste to měli z velký části připravený na tu páteční schůzku

**Comment by OndrejPittl** [comment]
Super, díky :+1:

**Comment by Sekiphp** [comment]
Jak na to koukám, tak za specifikaci budeme muset nakopírovat nějaké prohlášení, které za nás podepíšu já + musí to podepsat zadavatel :)

**Comment by jhomolka** [comment]
přibyla složka specifikace/ kde jsou pro ni všechny potřebné dokumenty
