### ISSUE TITLE
GUI v JavaFX

### ISSUE THREAD

**Issue by Sekiphp** [Sekiphp/ZSWI_monitoring#17]
Pro: Honza Kohlíček

Ahoj, potřebuji, abys vytvořil uživatelské rozhraní přibližně dle obrázku, který máme v adresáři specifikace (najdeš ho tam po syncnutí projektu). Udělej to jenom s tím rozdílem, že ty tlačítka, které jsou navržené v pravé části okna dej do menu.

**Comment by OndrejPittl** [comment]
Jsou (do Eclipse) nějaké pluginy na JavaFX, případně jiný SW, co generuje kód.. kdyžtak i tohle by bylo řešením :-)

**Comment by kohlicekjan** [comment]
OK, pracuje se na tom.

**Comment by Sekiphp** [comment]
Zaznamenal jsem nějaký commit, ale pracuju na specifikaci. Jak to zatím vypadá?

**Comment by kohlicekjan** [comment]
Udělal jsem rozložení GUI, funkčnost se musí ještě přidat.
