### ISSUE TITLE
Strávený čas na projektu

### ISSUE THREAD

**Issue by Sekiphp** [Sekiphp/ZSWI_monitoring#20]
V tomto topicu si prosím každý založte příspěvek a do něj si piště kolik vám jaká činnost zabrala kolik času. Jak víte na minulé iteraci jsme na to byli tázáni :) 

Poznámka: každý jen jeden příspěvek a ten průběžně editujte ;)

**Comment by Sekiphp** [comment]
Luboš Hubáček
- I. schůzka se zadavatelem   - 2 hodiny
- prototyp v čisté Javě             - 3 hodiny
- II. schůzka se zadavatelem  - 2 hodiny
- psaní specifikace                  - 9 hodin
- Ganttův diagram                   - 2 hodiny
- WBS                                      - 0,5 hodin
- organizační činnosti  (řízení týmu)            - 9.5 hodin
- učení se nových technologií
  - Maven - 2 hodiny
  - SpringWS - 8 hodin
  - Log4J - 3 hodiny
  - Git workshop - 2 hodiny
- III. schůzka se zadavatelem  - 2 hodiny
- příprava na třetí iteraci - 5 hodin
- doprogramování kódu pro jednu neimplementovanou instanci + další drobné zásahy - 1 hodina 
- konzultace před druhou iterací v týmu - 2 hodina
- správa issues a dokopávání některých členů týmu k jejich doplňování - 0.5 hodiny
- založení wiki stránky o testování produktu - 1 hodina
- IV. schůzka se zadavatelem - 1.5 hodiny
- testování programu - 3 hodiny
- programování - 4 hodiny
- wiki stránka "Popis, ovládání programu" - 1 hodina
- finální úpravy kódu - 0.5h
- wiki stránka "Uživatelská příručka" - 1.5h
- poslední schůzka se zadavatelem - 1h
- poslední úpravy zdrojového kódu - 1h

============= 68h =============
Poslední změna: 12.5.2015

**Comment by pkozler** [comment]
Petr Kozler
- studium, testování a výuka instalace a ovládání nástroje Maven — 4 hodiny
- studium, testování a výuka práce s knihovnou Log4j 2 — 6 hodin
- studium a testování technologie SpringWS — 10 hodin
- boj za správný tvar souboru .gitignore — 5 hodin
- II. schůzka se zadavatelem — 2 hodiny
- psaní specifikace — 4 hodiny
- III. schůzka se zadavatelem — 2 hodiny
- doprogramování kódu pro logování — 6 hodin
- průběžné testování aplikace — 4 hodiny
- příprava na 3. iteraci — 2 hodiny
- IV. schůzka se zadavatelem — 1.5 hodiny
- korektura Wiki stránky — 1 hodina
- zpřehlednění kódu a adresářové struktury — 0.5 hodiny
- úprava konfigurace pro logování, doplnění logovacích hlášek — 3 hodiny
- testování (manuální) — 2 hodiny
- úprava souboru .gitignore, zpřehlednění adresářové struktury — 2 hodiny 
- korektura a doplnění Wiki stránky — 1 hodina
- přidání ikony — 2.5 hodiny
- refaktoring kódu pro logování — 1 hodina 
- změna nastavení výstupního adresáře logů — 0.5 hodiny
- doplnění uživatelské příručky 0.5 hodiny
- čekání - 0.5 hodiny
- poslední schůzka se zadavatelem - 1 hodina
- poslední úpravy zdrojového kódu - 2 hodiny

Celkem: 64 hodin
Poslední změna: 12.5.2015

**Comment by OndrejPittl** [comment]
Ondřej Pittl
- neustálý kontakt se zadavatelem (e-mailem, telefonicky, osobně) — 5 hodiny
- příprava před první schůzkou (příprava otázek) — 1 hodina
- I. schůzka se zadavatelem — 2 hodiny
- studie technologií + testování
  - Maven — 4 hodiny
  - SpringWS — (nevyčíslitelné) — 20 hodin
  - Log4J — 2 hodiny
  - GitHub workshop — 2 hodiny
- II. schůzka se zadavatelem — 2 hodiny
- korektura, stylistika textu specifikace, doplnění chybějících informací - 3 hodiny
- Ganttův diagram — 2 hodiny
- WBS — 0.5 hodiny
- organizační činnosti — 6 hodin
  - sjednávání schůzek
  - komunikace s týmem
  - zjišťování náležitostí projektu
- plány na iterací — 3.5 hodiny
  - informování členů týmu ohledně náležitostí
    - požadavky na specifikaci + její upřesnění
    - funkcionalita aplikace, apod.
- III. schůzka se zadavatelem — 3 hodiny
  - návrh implementace ve SpringWS
- příprava na třetí iteraci — 2 hodiny
- druhá polovina Objektového návrhu, doplnění informací, korektura, stylistika textu — 7 hodin
- IV. schůzka se zadavatelem — 1.5 hodiny
- kontinuální komunikace se serverem,
  individuální nastavení časových period aktualizací stavu,
  GUI v odděleném vlákně — 5 hodin
- JavaDocs — 1.5 hodiny
- příprava na čtvrtou iteraci — 0.5 hodiny
- dokončení uživatelského manuálu, doplnění chybějících částí, stylistika textu, korektura - 2 hodiny
- poslední schůzka se zadavatelem — 1 hodina
- poslední úpravy zdrojového kódu — 1 hodina
- analýza řešení chyb způsobených selháním správy projektu, vyhlášení krizové situace, <br>
  googlení řešení, realizace nalezených řešení, implementace a debug — 4 hodiny
- eliminace redundantního kódu polymorfismem, <br>
  změna přístupu k loggerům,  refactoring kódu — 2.5 hodiny 

celkem: 83.5 hodin

**Comment by jhomolka** [comment]
Jiří Homolka

Uceni s GitHubem + GitHub workshop - 3h
Kontrola specifikace - 1h
Příprava otázek na zadavatele - 3h
Studium nových technologií - Log4J - 3h
Studium nových technologií - Maven - 5h
Studium nových technologií - SpringWS - 7h 
Doprogramování instance Sessions_info - 8h
Doprogramování instance Memory_info - 3h
Komunikace s týmem - 3h
Příprava na třetí iteraci - 1h
Testování vhodného SW pro generování UML z kodu - 2h
IV. schůzka se zadavatelem - 1.5 h
Vytvoření Wiki stránky - 6 h

Celkem: 46,5 hodin

**Comment by kohlicekjan** [comment]
Jan Kohlíček

byrokracie - 2 hodin
1. schůzka se zadavatelem - 2 hodiny
Maven - 4 hodiny
SpringWS - 2 hodiny 
Log4J - 3 hodiny
GitHub workshop - 2 hodiny
byrokracie - 2 hodin
2. schůzka se zadavatelem - 2 hodiny
Rozložení GUI v javaFX - 4 hodiny
Dialog message v javaFX - 5 hodin
Prototyp GUI - 12 hodin
byrokracie  - 2 hodin
4. schůzka se zadavatelem - 1.5 hodiny
Ovládání filtru - 6 hodin 
Funkční filtr - 4 hodiny
byrokracie  - 2 hodin
Vylepšení dialogu - 3 hodiny
Přidání ukládání a nahrávání refresh periody - 4 hodiny
Změna GUI - 3 hodin
Zastavení auto scroll - 2 hodiny 
Kontrola url - 2 hodiny

Celkem 69,5 hodin

**Comment by Sekiphp** [comment]
Nechte toto issue otevřené a průběžně jej editujte dle potřeb!!!!
