### ISSUE TITLE
Honzo: Napojení GUI na skelet aplikace

### ISSUE THREAD

**Issue by Sekiphp** [Sekiphp/ZSWI_monitoring#24]
Ahoj Honzo!
Brzy už bude potřeba napojit funkční prototyp aplikace na GUI. Tipuju, že aplikace bude připravená zítra večer nebo nejpozději během pondělka. Zatím nemusí být všechno funkční, ale bylo by fajn, kdyby se logování vypisovalo aspoň v určené políčku ;)

Díky

**Comment by kohlicekjan** [comment]
OK, už teď jsem na tom začal pracovat.

**Comment by kohlicekjan** [comment]
Potřebuji vytvořit message dialog, ale javaFX je má až od verze java 8u40, což je nejnovější java, mám ji použit nebo využit dialog ze swingu?

**Comment by Sekiphp** [comment]
http://code.makery.ch/blog/javafx-2-dialogs/

Nešlo by použít tuhle utilitku?

**Comment by kohlicekjan** [comment]
Na tu jsem koukal, nevím jestli by bylo dobrý využívat další knihovnu, kvůli údržbě. Asi by bylo lepší použít novou javu, v budoucnu to bude mít lepší podporu.

**Comment by Sekiphp** [comment]
Tohle ničemu nebrání - pak to zkonzultujeme se zadavatelem
