### ISSUE TITLE
Jirko: Dopsat wiki

### ISSUE THREAD

**Issue by Sekiphp** [Sekiphp/ZSWI_monitoring#26]
Ahoj, jelikož minule se nás p. Mouček na iteraci ptal, zda-li máme wiki a bohužel jsme jí neměli hodilo by se už jí začít pomalu stavět. Chtělo by to vytvořit několik podstránek (mj. zjednodušenou specifikace - o co jde, použité technologie, popis tříd + okopírovat UML z objektového návrhu) + nebráním se ani dalším věcem :)

Myslíš, že by to šlo v horizontu týdne?

**Comment by jhomolka** [comment]
Ahoj, myslím si, že by to neměl být problém do týdne zvládnout. Pokusím se ale o to, aby to bylo co nejdříve

**Comment by OndrejPittl** [comment]
Ahoj, se mnou taky můžete počítat, rád pomůžu :)

**Comment by jhomolka** [comment]
Tak jsem se do toho dneska pustil, je to teda dost časově náročný .. kdyžtak se na to můžete už podívat a když napsat nějaký názory, co je tam třeba ještě dodělat a jaký informace, který již máme, tam jěště musíme dát

**Comment by OndrejPittl** [comment]
Wiki vypadá dobře :-) Do budoucna možná ještě rozšíříme o nové informace, zatím to shledávám splněným :+1:

**Comment by Sekiphp** [comment]
ano vypadá to dobře ;)
