### ISSUE TITLE
Informace z IV. schůzky

### ISSUE THREAD

**Issue by OndrejPittl** [Sekiphp/ZSWI_monitoring#28]
<strong>Vlákna</strong>
- každou komponentu do samostatného vlákna <strong>[bude asi v jednom]<strong>
- dát si pozor na synchronizaci vláken
- synchronizace: semafor?
- Thread group — hromadné řízení vláken
- GUI v odděleném vlákně <strong>[SOLVED]</strong>

<strong>Timer</strong>
- zajištění kontinuálního monitoringu komponent <strong>[SOLVED]</strong>
- pro každou službu (vlákno) konfigurovatelný interval <strong>[SOLVED]</strong>

<strong>Menu</strong>
- tlačíka start & stop <strong>[SOLVED]</strong>
  <strong>přidal bych na stejnou úroveň jako File button</strong>

<strong>Logování</strong>
- logovat stav aplikace <strong>[SOLVED]</strong>
  - 1x na terminál
  - plus do každého souboru

<strong>Dialogy</strong>
- zbyde-li čas, nativní dialogy (Java 8_40) <strong>[SOLVED]</strong>

**Comment by Sekiphp** [comment]
Prosím o info co už máme hotové a co nikoliv :)

**Comment by OndrejPittl** [comment]
hotovo :)
