### ISSUE TITLE
Petr: Doplnění chybějících logovacích hlášek

### ISSUE THREAD

**Issue by OndrejPittl** [Sekiphp/ZSWI_monitoring#29]
Ahoj, Petře, jelikož jsi implementoval logování, poprosím tě ještě o doplnění chybějících hlášek — tedy start a stop aplikace. O implementaci výpisu na terminál aplikace se postaráme s Honzou K. Jen podotýkám, že záznam o stavu aplikace musí být ve všech logovacích souborech<br> (více viz <em>Informace z IV. schůzky</em>).

**Comment by pkozler** [comment]
Mám pár dotazů:
1) Už jsou třídy EventHandlerů ve fázi, kdy můžu přidávat logovací hlášky, nebo se někde ještě bude něco přidávat, upravovat?
2) Co se týče hlášení o stavu aplikace v logovacích souborech pro jednotlivé instance PF - co všechno by měla zahrnovat? Postačí dosavadní hlášení o spuštění/ukončení aplikace a spuštění/pozastavení monitoringu, nebo tam mám ještě něco přidat?

**Comment by Sekiphp** [comment]
2) To by mělo zatím bohatě postačovat

**Comment by pkozler** [comment]
OK, doplnil jsem logovací hlášky do EventHandlerů.
