### ISSUE TITLE
Název týmu

### ISSUE THREAD

**Issue by OndrejPittl** [Sekiphp/ZSWI_monitoring#3]
Je třeba vymyslet jméno týmu. Nějaké návrhy?

**Comment by kohlicekjan** [comment]
A-Team

**Comment by Sekiphp** [comment]
Crosscafe team

**Comment by OndrejPittl** [comment]
S CrossCafe teamem souhlasím.

**Comment by kohlicekjan** [comment]
JJOPL - složeno z našich jmen

**Comment by pkozler** [comment]
Kohlíček: A nebo KHPKH. :)

Jinak mně je to buřt...

**Comment by jhomolka** [comment]
Jsem pro CrossCafe team

**Comment by Sekiphp** [comment]
3:2 => CrossCafe team

Stejně je to ale formalita, na které nezáleží ;)
