### ISSUE TITLE
Jan: GUI

### ISSUE THREAD

**Issue by OndrejPittl** [Sekiphp/ZSWI_monitoring#30]
Ahoj, Honzo,
GUI je poměrně velké sousto a vím, že jsi si nevěděl rady s jedním konkrétním ActionEventem, tak se na něj podívám taky, taky jsem s <strong>JavaFX</strong> už něco zkoušel, ale až budeš mít čas, určitě na to taky koukni.

**Comment by kohlicekjan** [comment]
Napadlo mě, že by ListView byl jednoduší, už jsem k tomu něco našel.
http://stackoverflow.com/questions/25347347/how-to-add-listener-to-the-checkbox-inside-a-listview-that-uses-checkboxlistcell

Mám to použít?

**Comment by Sekiphp** [comment]
Můžeš, v tomhle by neměl být problém, protože v tree je a bude stejně jen jedno zanoření. Pokud je to jednodušší na implementaci, tak jednoznačně toto :)

**Comment by OndrejPittl** [comment]
Hele pokud to půjde implementovat, tak to bude super, ten strom s CheckBoxTreeItems je tak strašně naprd. Žádná pořádná dokumentace, žádné příklady + nikdo to snad ještě nepoužil a to možná proto, že to ani nejde. To jsem toho prošel a vyzkoušel tolik a nic. :/

**Comment by kohlicekjan** [comment]
OK, pustím se do toho.

**Comment by Sekiphp** [comment]
Tak prosím ať je to co nejdříve :dart:

**Comment by kohlicekjan** [comment]
Je to hotový, jen nevím jak získat pole s názvy UrlFactory

**Comment by Sekiphp** [comment]
Tohle bude asi problém, protože obecně zadavatel nás svými požadavky nahnal někam, kde mi přijde, že aplikace není snadno rozšiřitelná. Zatím to tam napiš staticky, nedá se nic dělat. Na iteraci bychom měli mít 80% funkčnosti, což bysme měli mít. Na dalším meetu se zadavatelem se budeme muset poradit ohledně zlepšení případné rozšiřitelnosti programu.

Prosím, ať jsou změny  hotové dneska do 22 hodin, děkuji

**Comment by kohlicekjan** [comment]
Hotovo, můžete otestovat.

**Comment by OndrejPittl** [comment]
Luboš: 50 — 80 %, takže jsme úplně v pohodě :-)
Jan: Se spuštěním mám problém, Eclipse mi hlásí chybu v syntaxi.

**Comment by kohlicekjan** [comment]
Musíš mít java 8u40
