### ISSUE TITLE
Nefunkční program

### ISSUE THREAD

**Issue by Sekiphp** [Sekiphp/ZSWI_monitoring#32]
Ahoj, právě jsem spustil program na svém notebooku a po stisknutí tlačítka Start nebo Restore se začne normálně načítat, ale program se zasekne na sessions_info. 

Nejspíš je to z toho důvodu, že někdo smazal všechna data na příslušné PF instanci:
http://peerfile.eu:3000/api/mon/sessions_info

Chtělo by to tedy udělat, aby když program nenalezne žádná data pro danou instanci, aby pokračoval dál a nebrzdil další činnost programu.

**Comment by pkozler** [comment]
Mně se to zdá v pořádku, program se nezasekne - zdá se, že pouze nepřijme žádnou instanci Sessions info, protože žádná není (jak si můžete všimnout, Sessions count je na hodnotě 0), ale jinak může pokračovat normálně v činnosti.

**Comment by Sekiphp** [comment]
mě to právě nenačítá další instance

**Comment by pkozler** [comment]
Sessions info je (zatím) poslední, pokud se nemýlím. Po kliknutí na Restore nebo Pause -> Start se instance normálně načtou znova. Alespoň u mě to tak funguje.

**Comment by Sekiphp** [comment]
U mě je sessions_info jako druhé a další instance se už nenačtou

**Comment by OndrejPittl** [comment]
V nové verzi by už mělo všechno fungovat, uzavírám tedy issue.
(kdyžtak vytvoříme nové nebo opět otevřeme)
