### ISSUE TITLE
Hlášení z testování (dialogy při ukončení)

### ISSUE THREAD

**Issue by pkozler** [Sekiphp/ZSWI_monitoring#33]
Čas: 7. 4. v 9:30

Hlášení:
Dosavadní funkcionalita programu se zdá být bez problémů. Pouze použití dvou dialogů při ukončení aplikace (zvlášť pro uložení filtru a pro potvrzení ukončení) muže být uživatelsky nepřívětivé. Navrhuji sjednocení dialogů do jednoho s dotazem typu "Uložit filtr před ukončením?" a třemi možnostmi - Uložit (a ukončit), Neukládat (a ukončit), Storno (neukládat a neukončovat). 
V případě ukončení aplikace s výchozím nastavením filtrů bych dialog buď nezobrazoval vůbec (podle mě není třeba, neboť informace se ukládají průběžně automaticky do logů a jedná se o klientskou aplikaci, jejíž náhlé ukončení nebude mít vážné následky; ale je možné, že zadavatel požadoval něco jiného), a nebo bych například zobrazil jiný dialog pro potvrzení ukončení programu (nabízel by pouze možnost Ukončit a Neukončovat).

**Comment by kohlicekjan** [comment]
Mělo by to být hotové.
