### ISSUE TITLE
Komplexní testování a sledování činnosti programu

### ISSUE THREAD

**Issue by Sekiphp** [Sekiphp/ZSWI_monitoring#34]
OS: Windows 8.1
Commit: e485567ca1a8e05d23021a668d869c88e37c0aab

Po spuštění programu se zobrazí dialogové okno, ve kterém se na první pohled nic neděje. Ve velkém textfieldu by možná nebylo od věci zobrazit nějakou hlášku, že monitoring není zapnutý. Export filtrů jak před ukončením programu tak i při stisknutí tlačítka "Save as" se zdá být v pořádku. Jenom nevidím žádný rozdíl mezi funkčností tlačítka "Save" a "Save as", možná jsem na to jenom napřišel, takže budu rád za objasnění ;) (Pozn: dyštak se to bude muset napsat do wiki). Při dvojkliku na název instance v listu se zobrazí dialog na zadání času refreshe daných instancí (PS: opravdu je tam vhodná ta ikonka otazníčku?). Ať jsem ale zadával číslo jakékoliv, tak při opětovném dvojkliku tam byla již znovu předvyplněná sedmička. Možná by také bylo užitečné při exportu filtrů exportovat i tyto časy obnovování dat - při velkém množství instancí a nechtěném zavření programu, či pádu systému by nemuselo být zrovna příjemné zase ladit časy u všech instancí. Načtení exportovaných dat funguje korektně. Tlačítko pause nefunguje - po stisknutí sice z menu zmizí a zobrazí se místo něj tlačítko start, ale načítání dat probíhá i nadále. Pokud je načítání stále aktivní a chci rolovat výstupem, tak při jeho aktualizaci se textfiled uživateli zroluje opět nakonec - pokud by to bylo možné bylo by hezké zachovávat pozici, kam si uživatel najel a v případě, že byl na konci, tak ho posunovat na konec.

**Comment by Sekiphp** [comment]
Další návrh: Z názvu tlačítek save a save as je poznat, že něco ukládají ale na první pohled není jasné co. Nebylo by teda možná od věci je přejmenovat na save filter a save filter as.

**Comment by OndrejPittl** [comment]
Plus já vznáším návrh na přesun Start, Pause přímo do toho menu na stejnou úroveň jako File tlačítko.

**Comment by Sekiphp** [comment]
Souhlasím a ještě bych to doplnil návrhem na přidání ikonek k těmto tlačítkům, aby to bylo vizuálně hezčí a viditelné na první pohled. Jsem si vědom, že děláme seriózní aplikaci, ale není vhodné, aby byla příliš monolitická.
- Tlačítko Save jsem zakomentoval, ale kód jsem zatím nemazal.

**Comment by Sekiphp** [comment]
Další náhodně objevená chyba:
Pokud se snažím uložit filtr na umístění, kde už je filtr se stejným názvem dochází k hlášení že daná cesta neexistuje - děje se tak při použití tlačítek save i save as. Z tohoto důvodu bych udělal jedno centrální tlačítko save filter, které by umělo přepisovat staré soubory s uloženými filtry (se stejným názvem) a umělo by i vytvářet nové s custom názvem. Nic jiného podle mě třeba není.

Poznatek z kódu:
V reportu jsem psal, že program scrolluje v textfieldu vždy dolů, ale až nyní jsem si všiml, že je to vlastně jeho feature. Možná by nebylo od věci tohle zkonzultovat se zadavatelem.

**Comment by OndrejPittl** [comment]
REPORT BY Sekiphp:

OS: Windows 8.1
Commit: e485567

Po spuštění programu se zobrazí dialogové okno, ve kterém se na první pohled nic neděje. Ve velkém textfieldu by možná nebylo od věci zobrazit nějakou hlášku, že monitoring není zapnutý. Export filtrů jak před ukončením programu tak i při stisknutí tlačítka "Save as" se zdá být v pořádku. Jenom nevidím žádný rozdíl mezi funkčností tlačítka "Save" a "Save as", možná jsem na to jenom napřišel, takže budu rád za objasnění ;) (Pozn: dyštak se to bude muset napsat do wiki). <strike>Při dvojkliku na název instance v listu se zobrazí dialog na zadání času refreshe daných instancí (PS: opravdu je tam vhodná ta ikonka otazníčku?). Ať jsem ale zadával číslo jakékoliv, tak při opětovném dvojkliku tam byla již znovu předvyplněná sedmička.</strike> <strong>[SOLVED (ikonu přidává knihovna sama)]</strong> Možná by také bylo užitečné při exportu filtrů exportovat i tyto časy obnovování dat - při velkém množství instancí a nechtěném zavření programu, či pádu systému by nemuselo být zrovna příjemné zase ladit časy u všech instancí. Načtení exportovaných dat funguje korektně. <strike>Tlačítko pause nefunguje - po stisknutí sice z menu zmizí a zobrazí se místo něj tlačítko start, ale načítání dat probíhá i nadále.</strike> Pokud je načítání stále aktivní a chci rolovat výstupem, tak při jeho aktualizaci se textfiled uživateli zroluje opět nakonec - pokud by to bylo možné bylo by hezké zachovávat pozici, kam si uživatel najel a v případě, že byl na konci, tak ho posunovat na konec.

**Comment by kohlicekjan** [comment]
Tlačítka "Save" a "Save as" je rozdíl, "Save as" zobrazí okno pro vybraní cesty a uloží, "Save" uloží na již vybranou cestu, aby nemusel člověk znova vybírat cestu.
Je to tak ve všech programech.

**Comment by kohlicekjan** [comment]
OS: Windows 8.1
Commit: e485567

Po spuštění programu se zobrazí dialogové okno, ve kterém se na první pohled nic neděje. Ve velkém textfieldu by možná nebylo od věci zobrazit nějakou hlášku, že monitoring není zapnutý. <strike>Export filtrů jak před ukončením programu tak i při stisknutí tlačítka "Save as" se zdá být v pořádku. Jenom nevidím žádný rozdíl mezi funkčností tlačítka "Save" a "Save as", možná jsem na to jenom napřišel, takže budu rád za objasnění ;) (Pozn: dyštak se to bude muset napsat do wiki). Při dvojkliku na název instance v listu se zobrazí dialog na zadání času refreshe daných instancí (PS: opravdu je tam vhodná ta ikonka otazníčku?). Ať jsem ale zadával číslo jakékoliv, tak při opětovném dvojkliku tam byla již znovu předvyplněná sedmička.</strike> <strong>[SOLVED (ikonu přidává knihovna sama)]</strong> Možná by také bylo užitečné při exportu filtrů exportovat i tyto časy obnovování dat - při velkém množství instancí a nechtěném zavření programu, či pádu systému by nemuselo být zrovna příjemné zase ladit časy u všech instancí. Načtení exportovaných dat funguje korektně. <strike>Tlačítko pause nefunguje - po stisknutí sice z menu zmizí a zobrazí se místo něj tlačítko start, ale načítání dat probíhá i nadále.</strike> Pokud je načítání stále aktivní a chci rolovat výstupem, tak při jeho aktualizaci se textfiled uživateli zroluje opět nakonec - pokud by to bylo možné bylo by hezké zachovávat pozici, kam si uživatel najel a v případě, že byl na konci, tak ho posunovat na konec.  <strong>[ Na nastavení skrolování, jsem na javaFX nic nenašel, uživatel si bude muset dát pauzu ]</strong>

**Comment by OndrejPittl** [comment]
Co říkáte na nápad, aby tlačítko pause pouze změnilo nějaký příznak indikující běh appky, která se bude v Timeline kontrolovat při výpisu na obrazovku. Jde mi o to, program komponenty furt logoval a jen se to nevypsalo na obrazovku (a mohl tak uživatel skrolovat). Ale na druhou stranu nevím, zda to je dobrý nápad, v souborech pak budou jiné informace než na obrazovce. 
Nebo nějaký checkbox pro auto-scroll/manual-scroll?

**Comment by Sekiphp** [comment]
Poradíme se se zadavatelem ;) Dyštak si to připiš na nějaký seznam, co s ním potřebujeme konzultovat :) Zakládám na to nové issue
