### ISSUE TITLE
Konzultovat se zadavatelem

### ISSUE THREAD

**Issue by Sekiphp** [Sekiphp/ZSWI_monitoring#35]
1) Co říkáte na nápad, aby tlačítko pause pouze změnilo nějaký příznak indikující běh appky, která se bude v Timeline kontrolovat při výpisu na obrazovku. Jde mi o to, program komponenty furt logoval a jen se to nevypsalo na obrazovku (a mohl tak uživatel skrolovat). Ale na druhou stranu nevím, zda to je dobrý nápad, v souborech pak budou jiné informace než na obrazovce. 
Nebo nějaký checkbox pro auto-scroll/manual-scroll?

2) jak upravit GUI?

**Comment by OndrejPittl** [comment]
3) https://github.com/Sekiphp/ZSWI_monitoring/issues/39

**Comment by kohlicekjan** [comment]
Mohl by jsme použít <strong>StatusBar</strong>, muže obsahovat informace i tlačítka atd.

**Comment by Sekiphp** [comment]
OK, zkusil by ses teda podívat na to, jak v našem případě implementovat ten status bar?

**Comment by kohlicekjan** [comment]
Jo, co by měl všechno obsahovat, nebo mám udělat jen ukázku?

**Comment by Sekiphp** [comment]
Ideálně pokud by ses držel původní myšlenky - Chtěl jsem mít menu file (tak jak je teď) a vedle tlačítko na start a stop (přesunulo by se z toho podmenu File "o úroveň výš"). - tak kdyby se ti to povedlo v tomto duchu,. tak bych byl rád.

Případně udělej v projektu nový package, kde to vyzkoušíš, abysme měli dyštak kam downgradovat ;)

**Comment by kohlicekjan** [comment]
StatusBar jsem si musel vytvořit vlastní, protože JavaFX to neumí. Auto scroll se mi nepovedlo vypnout, a do MenuBar nejde vložit rovnou MenuItem. Kdyby to bylo špatný, tak to můžeš Revertnout
