### ISSUE TITLE
Naprogramovat

### ISSUE THREAD

**Issue by Sekiphp** [Sekiphp/ZSWI_monitoring#36]
<strike>1) Úprava dialogového okna při dvojkliku na instanci - LUBOŠ</strike>
2) Přesunutí tlačítka Start/Pause do lišty vedle tlačítka pause - JIRKA
<strike>3) Export času obnovování instancí společně s filtrem - HONZA</strike>
<strike>4) Šlo by programu přiřadit nějakou ikonku? (Vyzkoumat) - ONDRA</strike>
<strike>5) Přidat ikonku k tlačítku exit - PETR</strike>

**Comment by kohlicekjan** [comment]
Začal jsem pracovat na 3).

**Comment by kohlicekjan** [comment]
Mám hotovo, můžete o testovat 3)

**Comment by pkozler** [comment]
Začal jsem pracovat na úloze č. 5.

**Comment by pkozler** [comment]
Jsem hotov.
