### ISSUE TITLE
Zpřehlednění logu

### ISSUE THREAD

**Issue by kohlicekjan** [Sekiphp/ZSWI_monitoring#37]
Všimnul jsem si, že se tohle všude opakuje

``` java
if (logger.isDebugEnabled())
     logger.debug("nějaký text");
```

nešlo by to dát do jedné metody, byla by pak jednoduší i případná úprava.

**Comment by pkozler** [comment]
Šlo by to, můžu to udělat, ale každá třída má svůj logger a ten tedy bude třeba do té metody předávat - kam mám tu metodu umístit?

**Comment by Sekiphp** [comment]
Nemohlo by se teoreticky použít někde dědičnost? Byla by například hlavní logovací třída a od té by dědily sublogovací třídy pro každou z instancí.

**Comment by pkozler** [comment]
To by se loggery musely buď vytvářet instančně, pokud se nemýlím (což mi připadá zbytečné), a nebo by se tak jako tak musely loggery zděděné metodě předávat, pak dědičnost postrádá význam. Nejvhodnější je asi vytvořit třídu s jedinou statickou metodou, kam se loggery budou předávat.

**Comment by pkozler** [comment]
Dokončil jsem zpřehlednění logovacího kódu.
