### ISSUE TITLE
Co je testovací protokol

### ISSUE THREAD

**Issue by Sekiphp** [Sekiphp/ZSWI_monitoring#38]
Ptal jsem se co je testovací protokol a zjistil jsem:

"Dobrý den,

Testovací protokol nemá žádnou pevnou formu, bude obsahovat seznam provedených testů včetně jejich typu, popisu a výsledků v rozumně čitelné formě. S pozdravem RM."

**Comment by OndrejPittl** [comment]
Takže něco takového, jako jsme si mysleli – soubor reportů + teda navíc typy testů.. tak aspoň, že tak.. :)
