### ISSUE TITLE
BUG: Logování do souborů

### ISSUE THREAD

**Issue by OndrejPittl** [Sekiphp/ZSWI_monitoring#39]
- Z nějakého důvodu se při logování do souboru zapisuje logovací hláška 2x.
  2015.04.22 17:39:51 [INFO - InstanceId.setInstance_id()] - Setting instance_id: PFT
  2015.04.22 17:39:51 [INFO - InstanceId.getInstance_id()] - Getting instance_id: PFT
  - Nicméně ne vždy se jedná o duplicitu: <br>
    2015.04.22 17:40:05 [INFO - SystemLoad.setSystem_load()] - Setting system_load: 0.0
    2015.04.22 17:40:05 [INFO - SystemLoad.getSystem_load()] - Getting system_load: 0.51
    2015.04.22 17:40:12 [INFO - SystemLoad.setSystem_load()] - Setting system_load: 0.0
    2015.04.22 17:40:12 [INFO - SystemLoad.getSystem_load()] - Getting system_load: 0.47

**Comment by pkozler** [comment]
Nikde nevidím duplicitu, jednou se vypisuje stav v getru a podruhé v setru. Atribut v InstanceId a SystemLoad se vypisuje stejným způsobem, domnívám se tedy, že se nejedná o chybu, ale vlastnost těch výpisů.

**Comment by OndrejPittl** [comment]
Možná by bylo vhodný tuhle featuru zkonzultovat, připisuju na seznam.
