### ISSUE TITLE
Kontakty

### ISSUE THREAD

**Issue by kohlicekjan** [Sekiphp/ZSWI_monitoring#4]
Zadejte jsem svoje kontakty.

**Comment by kohlicekjan** [comment]
Jan Kohlíček: 
    email: kohlicejan@gmail.com
    skype: kohl-j
    telefon: 733203562

**Comment by Sekiphp** [comment]
Luboš Hubáček
email: lubos.hubacek@diginex.cz
skype: Seki.php
telefon: 736 15 14 17

**Comment by OndrejPittl** [comment]
Ondřej Pittl
email: ondrej.pittl@gmail.com
skype: někde bych kdyžtak vyhrabal
telefon: 728 820 850

**Comment by pkozler** [comment]
Petr Kozler:
Email (ZČU): pkozler@students.zcu.cz (tuhle adresu pro záležitosti související se studiem preferuji)
Dropbox / alternativní email: pkozler.email@gmail.com
Skype / alternativní email 2: pk.outlook@outlook.cz
Telefon: 605 589 359

**Comment by jhomolka** [comment]
Jiří Homolka:
email: jiri.homolka22@gmail.com
telefon: 725 752 608
