### ISSUE TITLE
Úprava podstránky na wiki

### ISSUE THREAD

**Issue by Sekiphp** [Sekiphp/ZSWI_monitoring#40]
Na wiki jsem udělal novou sekci: https://github.com/Sekiphp/ZSWI_monitoring/wiki/Popis,-ovl%C3%A1d%C3%A1n%C3%AD-programu

Prosím o jazykovou kontrolu a dopsání věcí, co jsme nevěděl.

**Comment by pkozler** [comment]
Provedl jsem korekturu a aktualizaci obsahu stránky. Údaj o výstupním adresáři pro logovací soubory jsem zatím nedoplňoval -  napadlo mě, zda by nebylo vhodné, aby aplikace umožňovala jeho nastavení. Více v issue https://github.com/Sekiphp/ZSWI_monitoring/issues/42.
