### ISSUE TITLE
BUG: Pád appky

### ISSUE THREAD

**Issue by OndrejPittl** [Sekiphp/ZSWI_monitoring#41]
Při příliš dlouhé době čekání na response serveru appka padá s chybou:
<em>I/O error on GET request for "http://peerfile.eu:3000/api/mon/system_load": <br>Connection timed out: connect</em>

Tj. je-li zdroj nedostupný (nešlo stránku zobrazit ani v internetovém prohlížeči, stejná chyba), vyprší čas požadavku a appka vykazuje výše zmíněnou chybu a s hláškou <em>Program neodpovídá</em> padá.

![image](https://cloud.githubusercontent.com/assets/9462490/7287342/f76dfd6a-e953-11e4-9660-d4cd94935d37.png)

**Comment by Sekiphp** [comment]
Máš ponětí jak dlouhá je ta doba čekání? 

Návrh řešení:
Nová konstanta s celočíselnou hodnotou indikující počet vteřin, po kterých pokud se nepodaří získat odpověď se zaloguje hláška, že instance není dostupná.

**Comment by Sekiphp** [comment]
Koukám, že nám vypli celý server PF, takže pro žádnou instanci nezískáme response. Aby nám nepadala aplikace, tak jsem to oTryCatchoval. Do catche to ale stejně skočí až vyprší execution time toho webu, takže by ho to chtělo někde přenastavit. jenže když bychom ho dali malej a sypal by hodně dat, tak by to taky mohlo teoreticky spadnout do catche.

Nevíte, zdali by šlo nějak načítat hlavičky co posílá web browseru - například HTTP 200 - OK? Podle toho bysme mohli určit jestli skočit na další instanci nebo pokračovat v získávání dat z té staré

**Comment by kohlicekjan** [comment]
Problém je, že na adrese nic není, takže žádný sever ti hlavičku nemůže vrátit.

**Comment by Sekiphp** [comment]
To je blbost ne? To musí něco vrátit. Jak jinak třeba browser pozná, že stránka neni dostupná a řekne ti to za vteřinku? To je spíš záležitost serveru, kterej musí browseru nějakym způsobem říct, že tam nic neni.

**Comment by kohlicekjan** [comment]
Tohle mi napíše Chrome: "Prohlížeči Google Chrome se nepodařilo načíst stránku, protože odezva serveru peerfile.eu byla příliš dlouhá. Webové stránky možná nejsou v provozu nebo máte potíže s připojením k internetu.", proste nedostane žádnou odpověď.

**Comment by Sekiphp** [comment]
Tak co zkusit stránku pingnout? Ping mi to vrátí do půl vteřiny ;) Spring je takový pěkný FW, tak by to mohl umět, nebo se na něj naštvu! :D

**Comment by kohlicekjan** [comment]
Taky mi to odpoví, když dám port 80 na 3000 ani ťuk.

**Comment by Sekiphp** [comment]
kohlicekjan - vyresil problem pingnutim url, jak bylo nekolikrat nadhozeno jako mozne reseni
