### ISSUE TITLE
Možnost nastavení výstupního adresáře pro logy

### ISSUE THREAD

**Issue by pkozler** [Sekiphp/ZSWI_monitoring#42]
Napadlo mě, zda by nebylo vhodné, aby aplikace umožňovala nastavení výstupního adresáře pro logovací soubory? Zatím je jím kořenový adresář spustitelného souboru aplikace (logy se ukládají na stejnou úroveň, jako spustitelný .jar soubor), což mně osobně nepřipadá přehledné.
Další možností by bylo ukládat soubory do nějaké složky s přednastaveným názvem, např. 'logs' která by se vytvořila na úrovni .jar souboru. Toto řešení je méně obecné, ale implementačně jednodušší (možno snadno nastavit v konfiguračním souboru Log4J).

**Comment by Sekiphp** [comment]
Zvolil bych zatím tu druhou možnost :) Pokud bys to stihl do iterace bylo by to fajn.

**Comment by pkozler** [comment]
Hotovo + aktualizoval jsem stránku na Wiki.
