### ISSUE TITLE
Co nám chybí a jak dál

### ISSUE THREAD

**Issue by Sekiphp** [Sekiphp/ZSWI_monitoring#44]
<strike> Resty z minulé iterace:</strike> 
- <strike>vytištěný testovací protokol</strike>
- <strike>vytištěný plán páté itetrace</strike>

<strike> Co je třeba udělat do úterka:</strike> 
- <strike> vyřešit timeouty - Kozler nebo Kohlíček (ideálně do pondělí)</strike>
- <strike> napsat uživatelský manuál</strike>
- <strike> Vytvořte release + zkontrolujte, jestli jsou k dispozici veškeré kódy + dokumentace</strike> 

<strike> Schůzka se zadavatelem:</strike> 
- <strike>nechat ho ještě jednou otestovat</strike>
- <strike>donutit ho zapnout PF</strike>
- <strike>Získejte od zadavatele podepsaný předávací protokol, využijte následující dokument
- https://github.com/Sekiphp/ZSWI_monitoring/issues/39</strike>

<strike> Pátá (poslední iterace):</strike> 
- <strike> dostavit by se měl asi celý tým, pokud chcete zápočty (jestli je dostaneme)</strike> 
- <strike>přinést vytištěné resty z minula (Ondo díky)</strike>
- <strike> Přineste vytištěný manuál (poslední revize) + předávácí protokol podepsaný</strike> 

Prezentace (poslední přednáška):
- prezentujte (technicky prodejte) Vaši práci - prezentace maximálně 7 minut dlouhá (.pdf či .ppt).
- klidně to odprezentuju sám, ale bylo by dobrý kdyby tam šel se mnou alespoň Ondra

**Comment by kohlicekjan** [comment]
Myslím, že problém s timeouty je vyřešen, ale jiným způsobem.
Pořád nevím, jak zastavit autoscroll.

**Comment by pkozler** [comment]
A nešel by u toho scrollování prozatím zvolit trochu opačný přístup? Myslím zapamatovat si aktuální pozici (před výpisem) a ihned po výpisu se na ni automaticky přesunout.

**Comment by Sekiphp** [comment]
Už dvakrát jsem říkal, že autoscroll necháme být ;)

**Comment by Sekiphp** [comment]
Zkontrolute / doplňte uživatelskou příručku ve wiki:

https://github.com/Sekiphp/ZSWI_monitoring/wiki/U%C5%BEivatelsk%C3%A1-p%C5%99%C3%ADru%C4%8Dka-%5BCZ%5D

**Comment by Sekiphp** [comment]
Schůzka se zadavatelem - vyhodit "duplicitní" logy - getry a setry, co se volají za sebou, tak zalogovat jen jednou

**Comment by Sekiphp** [comment]
Máte ponětí, co dáme do prezentace? :D Budeme dělat živou ukázku?
