### ISSUE TITLE
Roman Řezáč — Info o projektu

### ISSUE THREAD

**Issue by OndrejPittl** [Sekiphp/ZSWI_monitoring#6]
Tato informace je od zadavatele:

Dokumentace k API je v priloze a testovaci instance PeerFile bezi na adrese: http://peerfile.eu:4000
Sluzbu je mozno otestovat napriklad takto:
curl --request GET -D- http://peerfile.eu:4000/api/mon/instance_id

Instance PF je spolecna pro oba ZCU projekty (JET a ZSWI).

Dokumentaci se pokusím procpat jako fyzický soubor repozitáře.

**Comment by Sekiphp** [comment]
KIV/JET - předmět o java EE (asi tam mají podobnou práci jak my tady)
PF - Peer File
Jinak z ostatního bohužel moc moudrý nejsem :(

**Comment by kohlicekjan** [comment]
Pamatuji si to dobře že máme použit Log4j? Protože je v úkolu z OKS.

**Comment by OndrejPittl** [comment]
Jojo, Log4J :+1:
